Partial Public Class Zml
    Const importsTag = "imports"
    Const usingTag = "using"
    Const namespaceTag = "namespace"
    Const helpersTag = "helpers"
    Const layoutTag = "layout"
    Const pageTag = "page"
    Const modelTag = "model"
    Const setTag = "set"
    Const getTag = "get"
    Const declareTag = "declare"
    Const viewtitleTag = "viewtitle"
    Const commentTag = "comment"
    Const forTag = "for"
    Const foreachTag = "foreach"
    Const ifTag = "if"
    Const thenTag = "then"
    Const elseifTag = "elseif"
    Const elseTag = "else"

    Const aspHelperPrefix = "asp-"
    Const pageHelperPrefix = "asp-page"
    Const atModel = "@Model"
    Const AtPage = "@page"
    Const AtUsing = "@using"
    Const AtNamespace = "@namespace"
    Const ModelKeyword = "Model"

    Const nsAttr = "ns"
    Const addAttr = "add"
    Const pageAttr = "page"
    Const routeAttr = "route"
    Const objectAttr = "object"
    Const typeAttr = "type"
    Const varAttr = "var"
    Const keyAttr = "key"
    Const valueAttr = "value"
    Const toAttr = "to"
    Const stepAttr = "step"
    Const whileattr = "while"
    Const letAttr = "let"
    Const inAttr = "in"
    Const conditionAttr = "condition"

End Class
